language: java
jdk: oraclejdk11
os: linux
dist: trusty
after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "xcesco"
    token: $SONAR_TOKEN # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn -Dkripton.debug=false -Dsonar.projectName="kripton" clean cobertura:cobertura org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
