package sqlite.kripton60;

import com.abubusoft.kripton.android.sqlite.BindDaoFactory;

/**
 * <p>
 * Represents dao factory interface for BeanDataSource.
 * This class expose database interface through Dao attribute.
 * </p>
 *
 * <p><strong>This class is generated by Kripton Annotation Processor (development)</strong></p>
 *
 * @since Tue Mar 13 21:51:22 CET 2018
 * @see BeanDataSource
 * @see BeanDao
 * @see BeanDaoImpl
 * @see Bean
 */
public interface BindBeanDaoFactory extends BindDaoFactory {
  /**
   *
   * retrieve dao BeanDao
   */
  BeanDaoImpl getBeanDao();
}
