package com.abubusoft.kripton.android.sqlite;

import com.abubusoft.kripton.android.annotation.BinderDatabaseSchema;

/**
 * Marker interface for DAO factory. This interface is implemented by class generated by {@link BinderDatabaseSchema}.
 * 
 * @author xcesco
 *
 */
public interface DaoFactory {

}
