package com.abubusoft.kripton.android.orm;

import com.abubusoft.kripton.android.SQLiteModificationType;

/**
 * Rapresents operations generated by insert, update, delete operations on
 * tables.
 * 
 * In INSERT case, value is the id of the object.
 * 
 * In UPDATE, DELETE situation, it is the number of affected rows.
 * 
 * @author Francesco Benincasa (info@abubusoft.com)
 *
 */
public class SQLiteEvent {

	public SQLiteEvent(SQLiteModificationType operationType, long value) {
		this.operationType = operationType;
		this.value = value;
	}

	public final SQLiteModificationType operationType;
	public final long value;

	public static SQLiteEvent createInsert(long result) {
		return new SQLiteEvent(SQLiteModificationType.INSERT, result);
	}

	public static SQLiteEvent createUpdate(long result) {
		return new SQLiteEvent(SQLiteModificationType.UPDATE, result);
	}

	public static SQLiteEvent createDelete(long result) {
		return new SQLiteEvent(SQLiteModificationType.DELETE, result);
	}
}
