package com.abubusoft.kripton.android.sqlite;

import com.abubusoft.kripton.android.annotation.BindDataSource;

/**
 * Marker interface for DAO factory. This interface is implemented by class generated by {@link BindDataSource}.
 * 
 * @author xcesco
 *
 */
public interface BindDaoFactory {

}
