/*******************************************************************************
 * Copyright 2015, 2017 Francesco Benincasa (info@abubusoft.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.abubusoft.kripton.android.sqlite;

import com.abubusoft.kripton.android.annotation.BindDataSource;

/**
 * Marker interface for DAO factory. This interface is implemented by class generated by {@link BindDataSource}.
 * 
 * @author Francesco Benincasa (info@abubusoft.com)
 *
 */
public interface BindDaoFactory {
	
	/**
	 * <p>Retrieve the Dao array.</p>
	 * 
	 * @return
	 */
	Dao[] daos();
	

}
