package com.abubusoft.kripton.android.sqlite;

import com.abubusoft.kripton.android.SqlModificationType;

/**
 * Rapresents operations generated by insert, update, delete operations on
 * tables.
 * 
 * In INSERT case, value is the id of the object.
 * 
 * In UPDATE, DELETE situation, it is the number of affected rows.
 * 
 * @author Francesco Benincasa (info@abubusoft.com)
 *
 */
public class SQLiteEvent {

	public SQLiteEvent(SqlModificationType operationType, long value) {
		this.operationType = operationType;
		this.value = value;
	}

	public final SqlModificationType operationType;
	public final long value;

	public static SQLiteEvent createInsert(long result) {
		return new SQLiteEvent(SqlModificationType.INSERT, result);
	}

	public static SQLiteEvent createUpdate(long result) {
		return new SQLiteEvent(SqlModificationType.UPDATE, result);
	}

	public static SQLiteEvent createDelete(long result) {
		return new SQLiteEvent(SqlModificationType.DELETE, result);
	}
}
