package com.abubusoft.kripton.processor.sqlite;

import static com.abubusoft.kripton.processor.core.reflect.TypeUtility.typeName;

import java.util.Date;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.PackageElement;
import javax.lang.model.util.Elements;

import com.abubusoft.kripton.android.annotation.BindDelete;
import com.abubusoft.kripton.android.annotation.BindInsert;
import com.abubusoft.kripton.android.annotation.BindSelect;
import com.abubusoft.kripton.android.annotation.BindUpdate;
import com.abubusoft.kripton.android.sqlite.AbstractBindDao;
import com.abubusoft.kripton.common.StringUtil;
import com.abubusoft.kripton.processor.sqlite.exceptions.MethodWithoutSupportedAnnotationException;
import com.abubusoft.kripton.processor.sqlite.model.SQLDaoDefinition;
import com.abubusoft.kripton.processor.sqlite.model.SQLiteDatabaseSchema;
import com.abubusoft.kripton.processor.sqlite.model.SQLiteModelElementVisitor;
import com.abubusoft.kripton.processor.sqlite.model.SQLiteModelMethod;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.TypeSpec.Builder;

/**
 * Dao generator
 * 
 * @author xcesco
 *
 */
public class BindDaoBuilder implements SQLiteModelElementVisitor {

	public static final String PREFIX = "Bind";
	protected Elements elementUtils;
	protected Filer filer;
	private Builder builder;
	private SQLDaoDefinition currentDaoDefinition;
	
	public BindDaoBuilder(SQLiteDatabaseSchema model, Elements elementUtils, Filer filer) {
		this.elementUtils = elementUtils;
		this.filer = filer;
	}

	public static void execute(Elements elementUtils, Filer filer, SQLiteDatabaseSchema model) throws Exception {
		BindDaoBuilder visitor = new BindDaoBuilder(model, elementUtils, filer);

		for (SQLDaoDefinition item : model.getCollection()) {
			item.accept(visitor);
		}
	}

	@Override
	public void visit(SQLDaoDefinition value) throws Exception {
		currentDaoDefinition = value;

		String classTableName = value.getName();
		classTableName = PREFIX + classTableName;

		PackageElement pkg = elementUtils.getPackageOf(value.getElement());
		String packageName = pkg.isUnnamed() ? null : pkg.getQualifiedName().toString();

		builder = TypeSpec.classBuilder(classTableName).superclass(AbstractBindDao.class).addSuperinterface(typeName(value.getElement())).addModifiers(Modifier.PUBLIC);
		// builder.addAnnotation(AnnotationSpec.builder(SQLDaoImplementation.class).addMember("schema", CodeBlock.of("$T", model.getElement().asType())).build());
		// generiamo il javadoc contenente la data di generazione della classe
		builder.addJavadoc("Generated by Kripton Library.\n\n");
		builder.addJavadoc("@since $L\n\n", (new Date()).toString());				
	
		// define column name set
		for (SQLiteModelMethod item : value.getCollection()) {
			item.accept(this);
		}

		TypeSpec typeSpec = builder.build();
		//BindDatabaseProcessor.info("WRITE " + typeSpec.name);
		
		JavaFile.Builder fileBuilder = JavaFile.builder(packageName, typeSpec);
		fileBuilder.skipJavaLangImports(true);
		
		fileBuilder.build().writeTo(filer);
	}

	@Override
	public void visit(SQLiteModelMethod value) throws Exception {
		if (value.getAnnotation(BindInsert.class) != null) {
			SQLiteInsertBuilder.generate(elementUtils, builder, value);
		} else if (value.getAnnotation(BindUpdate.class) != null) {
			SQLiteModifyBuilder.generate(elementUtils, builder, value, true);		
		} else if (value.getAnnotation(BindDelete.class) != null) {
			SQLiteModifyBuilder.generate(elementUtils, builder, value, false);
		} else if (value.getAnnotation(BindSelect.class) != null) {
			SQLiteSelectBuilder.generate(elementUtils, builder, value);
		} else {
			// method without supported annotation
			throw (new MethodWithoutSupportedAnnotationException(currentDaoDefinition, value));
		}

	}


}
