package com.abubusoft.kripton.processor.sqlite;

import java.util.Date;

import com.abubusoft.kripton.processor.BindDataSourceProcessor;
import com.abubusoft.kripton.processor.Version;
import com.squareup.javapoet.TypeSpec.Builder;

public abstract class JavadocUtility {
	/**
	 * @param builder 
	 * 
	 */
	public static void generateJavadocGeneratedBy(Builder builder) {
		builder.addJavadoc("<p><strong>This class is generated by Kripton Annotation Processor ($L)</strong></p>\n\n", Version.getVersion());
		if (!BindDataSourceProcessor.DEVELOP_MODE) {
			builder.addJavadoc(" @since $L\n", (new Date()).toString());
		}
	}
}
